src/FleetBattles/Controllers/ACPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FleetBattles.Controllers
{
    [Authorize(Roles="Admin")]
    public class ACPController : Controller
    {
        // GET: ACP
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/FleetBattles/Controllers/ChannelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FleetBattles.Data;
using FleetBattles.Models;
using Microsoft.AspNetCore.Authorization;

namespace FleetBattles.Controllers
{
    [Authorize(Roles="Admin")]
    public class ChannelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ChannelController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Channel
        public async Task<IActionResult> Index()
        {
            return View(await _context.Channels.ToListAsync());
        }

        // GET: Channel/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.SingleOrDefaultAsync(m => m.ChannelId == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // GET: Channel/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Channel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ChannelId,Name,Color,IsPublic")] Channel channel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(channel);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(channel);
        }

        // GET: Channel/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.SingleOrDefaultAsync(m => m.ChannelId == id);
            if (channel == null)
            {
                return NotFound();
            }
            return View(channel);
        }

        // POST: Channel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ChannelId,Name,Color,IsPublic")] Channel channel)
        {
            if (id != channel.ChannelId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(channel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChannelExists(channel.ChannelId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(channel);
        }

        // GET: Channel/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var channel = await _context.Channels.SingleOrDefaultAsync(m => m.ChannelId == id);
            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var channel = await _context.Channels.SingleOrDefaultAsync(m => m.ChannelId == id);
            _context.Channels.Remove(channel);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ChannelExists(int id)
        {
            return _context.Channels.Any(e => e.ChannelId == id);
        }
    }
}

src/FleetBattles/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FleetBattles.Data;
using FleetBattles.Models;
using Microsoft.AspNetCore.Authorization;

namespace FleetBattles.Controllers
{
    [Authorize(Roles="Admin")]
    public class PlayerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayerController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Player
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ApplicationUser.Include(a => a.Faction).Include(a => a.Race);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Player/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // GET: Player/Create
        public IActionResult Create()
        {
            ViewData["FactionId"] = new SelectList(_context.Factions, "FactionId", "Adjective");
            ViewData["RaceId"] = new SelectList(_context.Races, "RaceId", "Adjective");
            return View();
        }

        // POST: Player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AccessFailedCount,ConcurrencyStamp,DisplayName,Email,EmailConfirmed,FactionId,LockoutEnabled,LockoutEnd,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,RaceId,SecurityStamp,TwoFactorEnabled,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicationUser);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["FactionId"] = new SelectList(_context.Factions, "FactionId", "Adjective", applicationUser.FactionId);
            ViewData["RaceId"] = new SelectList(_context.Races, "RaceId", "Adjective", applicationUser.RaceId);
            return View(applicationUser);
        }

        // GET: Player/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            ViewData["FactionId"] = new SelectList(_context.Factions, "FactionId", "Adjective", applicationUser.FactionId);
            ViewData["RaceId"] = new SelectList(_context.Races, "RaceId", "Adjective", applicationUser.RaceId);
            return View(applicationUser);
        }

        // POST: Player/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,AccessFailedCount,ConcurrencyStamp,DisplayName,Email,EmailConfirmed,FactionId,LockoutEnabled,LockoutEnd,NormalizedEmail,NormalizedUserName,PasswordHash,PhoneNumber,PhoneNumberConfirmed,RaceId,SecurityStamp,TwoFactorEnabled,UserName")] ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicationUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicationUserExists(applicationUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["FactionId"] = new SelectList(_context.Factions, "FactionId", "Adjective", applicationUser.FactionId);
            ViewData["RaceId"] = new SelectList(_context.Races, "RaceId", "Adjective", applicationUser.RaceId);
            return View(applicationUser);
        }

        // GET: Player/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }

            return View(applicationUser);
        }

        // POST: Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = await _context.ApplicationUser.SingleOrDefaultAsync(m => m.Id == id);
            _context.ApplicationUser.Remove(applicationUser);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ApplicationUserExists(string id)
        {
            return _context.ApplicationUser.Any(e => e.Id == id);
        }
    }
}

src/FleetBattles/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FleetBattles.Data;
using FleetBattles.Models;
using Microsoft.AspNetCore.Authorization;

namespace FleetBattles.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RaceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RaceController(ApplicationDbContext context)
        {
            _context = context;    //k
        }

        // GET: Race
        public async Task<IActionResult> Index()
        {
            return View(await _context.Races.ToListAsync());
        }

        // GET: Race/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.SingleOrDefaultAsync(m => m.RaceId == id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // GET: Race/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Race/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RaceId,Adjective,AvatarURL,Name")] Race race)
        {
            if (ModelState.IsValid)
            {
                _context.Add(race);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(race);
        }

        // GET: Race/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.SingleOrDefaultAsync(m => m.RaceId == id);
            if (race == null)
            {
                return NotFound();
            }
            return View(race);
        }

        // POST: Race/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RaceId,Adjective,AvatarURL,Name")] Race race)
        {
            if (id != race.RaceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(race);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RaceExists(race.RaceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(race);
        }

        // GET: Race/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var race = await _context.Races.SingleOrDefaultAsync(m => m.RaceId == id);
            if (race == null)
            {
                return NotFound();
            }

            return View(race);
        }

        // POST: Race/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var race = await _context.Races.SingleOrDefaultAsync(m => m.RaceId == id);
            _context.Races.Remove(race);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool RaceExists(int id)
        {
            return _context.Races.Any(e => e.RaceId == id);
        }
    }
}

src/FleetBattles/Views/Shared/_ACPNav.cshtml
<div class="navbar-collapse collapse" align="center" style="margin: 5px; margin-bottom: 10px;">
    <a asp-area="" asp-controller="Faction" asp-action="Index" class="T1">Factions</a>
    <a asp-area="" asp-controller="Race" asp-action="Index" class="T1">Races</a>
    <a asp-area="" asp-controller="Channel" asp-action="Index" class="T1">Channels</a>
    <a asp-area="" asp-controller="Player" asp-action="Index" class="T1">Players</a>
</div>

src/FleetBattles/Views/Shared/_IWLayout.cshtml
@using System

@inject SignInManager<ApplicationUser> ASignInManager
@inject UserManager<ApplicationUser> AUserManager
<HTML>
<HEAD>
    <LINK REL=STYLESHEET HREF=~/css/Style.css>
    <title>@ViewData["Title"] - Interstellar War: Free browser based space MMORPG (multiplayer online role-playing game)</title>
    <META NAME="Keywords" CONTENT="interstellar war, free, massive, massively, multiplayer, online, game, battle, space, mmog, mmorpg, role play, role playing, strategic, strategy, diplomacy">
    <META NAME="Description" CONTENT="A free browser based massively multiplayer online role-playing game set in space">
    <script type='text/javascript' src='http://finity.online/applications/cms/interface/external/external.js' id='ipsWidgetLoader'></script>
</HEAD>
<BODY>
    <TABLE>
        <TR>
            <TD width=182 class="C T">
                <TABLE class="W T1">
                    <TR><TD class=C><A href=http://www.interstellar-war.com/><IMG src="~/images/i/IWFB logo.gif"></A>
                        <BR>Interstellar Time: @TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time")).ToString("HH:mm")</TD></TR>
                </TABLE><img src=~/images/i/sp.gif height=4><TABLE class="W T1">
                   @if (!ASignInManager.IsSignedIn(User)) {
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <form asp-controller="Account" asp-action="Login" asp-route-returnurl="http://battles20160627075859.azurewebsites.net/" method="post">
                            <TR><TD class=R>Email :</TD><TD><INPUT name=Email tabindex=1 size=12 value=></TD><TD class=C rowspan=3><INPUT type=Submit value=Go! class=BTN><BR><INPUT name="RememberMe" tabindex=3 type=checkbox value="true" class=X><BR>Auto</TD></TR>
                            <TR><TD class=R>Pass :</TD><TD><INPUT name=Password tabindex=2 type=Password size=12></TD></TR>
                            <TR>
                                <TD colspan=2>
                                    <IMG src=~/images/i/li.gif><a asp-area="" asp-controller="Account" asp-action="Register">Create Account</a><BR>
                                    <IMG src=~/images/i/li.gif><a asp-area="" asp-controller="Account" asp-action="ForgotPassword">Lost password?</a>
                                </TD>
                            </TR>
                        </FORM>
                        }
</TABLE><IMG src=~/images/i/sp.gif height=4><TABLE class="W T1">
                    <TR><TH>Public Links</TH></TR>
                    <TR>
                        <TD>
                            <IMG src=~/images/i/li.gif><A href=Home.asp?ID =>Interstellar Home</A><BR>
                            <IMG src=~/images/i/li.gif><A href=Ranking.asp?ID =>Rankings</A><BR>
                            <IMG src=~/images/i/li.gif><A href=Guide.asp?ID =>Guide</A> | <A target=_blank href=/web/20070505100253/http://www.beast.za.net />Help Site</A> | <A href=Help.asp?P =Help&amp;ID =>Wiki</A><BR>

                            <IMG src=~/images/i/li.gif><A href=Story.asp?ID =>Story</A> | <A href=Community.asp?ID =>Community</A> | <A href=About.asp?ID =>About</A><BR>
                            <IMG src=~/images/i/li.gif><A href=Release.asp?ID =>Release Notes</A><BR>
                            <IMG src=~/images/i/li.gif><A href=Vote.asp target=_blank><B><U>Vote for us!</B></U></A>
                        </TD>
                    </TR>
                    <TR><TH>Private Links</TH></TR>
                    <TR>
                        <TD>
                            <IMG src=~/images/i/li.gif>Play Fleet Battles !<BR>
                            @if (User.IsInRole("Admin")) { 
                            <IMG src=~/images/i/li.gif><a asp-area="" asp-controller="ACP" asp-action="Index">Terrorize Users !</a><BR>
                            }
                            <IMG src=~/images/i/li.gif>Forums & Online Chat<BR>
</TD>
                    </TR>
                </TABLE>
            </TD>
            <TD width=4><IMG src=~/images/i/sp.gif width=4></TD>
            <TD width=813 class="T C">
                @RenderBody()
</TR><TR><TD class=C colspan=3>
    @{
        decimal timeInSeconds = ((decimal)(DateTime.Now.Ticks - ((DateTime) Context.Items["StartTime"]).Ticks)) / (decimal)TimeSpan.TicksPerSecond; ;
    }
    @timeInSeconds<BR>The game, content and mechanics are <a href="Copy.asp?ID=">copyright</a> © of the Original Interstellar War team 2005.
        </TD></TR></TABLE>
    @RenderSection("scripts", required: false)
</BODY>
</HTML>

src/FleetBattles/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.Extensibility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FleetBattles</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FleetBattles</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - FleetBattles</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>